language: python
python:
- 3.6.6
cache:
  directories:
  - "$HOME/.cache/pip"
env:
  global:
  - PACKAGE_NAME=wagtail-draftail-snippet
  - PIP_INDEX_URL=https://www.fool.com/a/apikey/$DEVPI_API_KEY/fool/packages/+simple/
install:
- pip install -U pip
- pip install .
script:
- python setup.py test
deploy:
  provider: pypi
  server: https://www.fool.com/a/apikey/$DEVPI_API_KEY/fool/packages/
  skip_upload_docs: true
  user: travisci
  on:
    tags: true
    python: '3.6'
  password:
    secure: rKwbHG7vo4zeOEHFcL/1JbaJzkfXYv8erbRle+B0Bg4GRhv7SAHzWdC2wot02H9Jnf0djT8LUbGAWKeUtTLA993rpPFiycVxAwaVkzNDqiiPCTi1KS6yuROhLWMcs69psJFYvxAsKHcuKcYzJyqOPTVGqfDiUxDGChCh2qQ99cM=
after_deploy:
  - "curl -X POST \"$PIP_INDEX_URL$PACKAGE_NAME/refresh\""
